### PR TITLE
add boolean argument to set_window_{above,below}

### PR DESCRIPTION
**Pull request by ghost**
There may be another way to do this that I've entirely missed. But to me, it looks like if a window spawns itself as above, there's no way using devilspie to remove that flag.

I'm using it to put Flash back on the normal layer after making it fullscreen in Openbox, which apparently doesn't detect the creation of the plugin_container, possibly because it technically already exists whenever plugin content exists in Firefox.

This breaks compatibility with existing scripts using these two functions as they now require an argument.

### CODE REVIEW

**Comment by gusnan** [comment]
I have started thinking about the current scripts - Would it be ok with you to make these functions either take no argument (which would default to behaviour as if the argument was "true"), or to take one argument (true or false)?

**Comment by ghost** [comment]
That would be better! I've updated the request with that functionality.

**Comment by gusnan** [comment]
Looks fine to me! Would you mind if I added you to the AUTHORS file? In that case - what name and e-mail would you like for me to add? (I will replace @ with (at) and . with (dot) so that you hopefully don't get spammed by bots searching the web for e-mail addresses.)

**Comment by ghost** [comment]
-snip-
Thanks!

**Pull request merged**
