### PR TITLE
updated pt_BR

### PR DESCRIPTION
**Pull request by hmbr**

### CODE REVIEW

**Comment by gusnan** [comment]
Is that a correct update? The two new strings are fuzzy and the content of one of the strings doesn't match the C-style formatting of the original. Also, since the new strings are fuzzy this won't make any changes to the results compared to before this commit.

**Comment by hmbr** [comment]
I missed a translation, ( and I wrote a wrong comment), now the fix is correct.

**Comment by gusnan** [comment]
I don't want to be a pest, but the two strings are still fuzzy, and will not show as translated in the resulting build. I don't want to go in and unfuzzy strings in a language that I don't know...

**Comment by hmbr** [comment]
No, you're right, I'm running here and I made some mistakes when I was reviewing the po, see if it is now correct.

**Comment by gusnan** [comment]
Thanks! I really appreciate your work! I am still waiting for another translation - I will give it some days, then I will make a new release.

**Pull request merged**
